config/routes.rb
Rails.application.routes.draw do
  #root 'courses#index' #old root
  root 'sessions#new' #new root -- for login page
  
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/moderator', to: 'control_panels#moderator'
  get '/registrar', to: 'control_panels#registrar'
  
  resources :course2users do
    
  end
  
  resources :courses do
    
  end
  resources :answers do
    member {get 'flag'}
    member {get 'unflag'}
    member {get 'upvote'}
    member {get 'downvote'}
  end
  resources :questions do
    member {get 'flag'}
    member {get 'unflag'}
    member {get 'upvote'}
    member {get 'downvote'}
  end
  resources :users do
    
  end
  
  
  #resources :questions, :shallow => true do 
  #  resources :answers
  #end
  
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end
  
  # GET /questions/boss
  def boss
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end
  
  def upvote
    @question = Question.find(params[:id])
    @question.increment!(:rep)
    @question.user.increment!(:rep)
    respond_to do |format|
      format.html { redirect_to @question, notice: 'Question was voted up!' }
      format.json { render :show, status: :ok, location: @question }
    end
  end
  
  def downvote
    @question = Question.find(params[:id])
    @question.decrement!(:rep)
    @question.user.decrement!(:rep)
    respond_to do |format|
      format.html { redirect_to @question, notice: 'Question was voted down!' }
      format.json { render :show, status: :ok, location: @question }
    end
  end
  
  #
  def flag
    @question = Question.find(params[:id])
    @question.update(is_flagged: 1)
    respond_to do |format|
      format.html { redirect_to @question, notice: 'Question was flagged.' }
      format.json { render :show, status: :ok, location: @question }
    end
  end
  
  #
  def unflag
    @question = Question.find(params[:id])
    @question.update(is_flagged: 0)
    respond_to do |format|
      format.html { redirect_to moderator_path, notice: 'Question was unflagged.' }
      format.json { render :show, status: :ok, location: @question }
    end
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.course_id = get_course?
    @question.user_id = get_user?
    
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to moderator_path, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the spoopy internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :question_id, :title)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <b>Posting in <%= Course.find_by(id: get_course?).name %></b><br><br>
  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/boss.html.erb
<p id="notice"><%= notice %></p>

<h1>NKUnet</h1>
<h2>Answers to Question</h2>

<%= link_to 'Home', questions_path %>
<%= link_to 'Users', users_path %>
<%= link_to 'New Question', new_question_path %>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>Question:</strong>
  <%= @question.question_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @question.user.name %>
</p>

<p>
  <strong>Answers:</strong>
  <%= link_to @question.answers.count , answers_path %>
</p>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <% if answer.question_id == @question.question_id %>
        <tr>
          <td><%= answer.content %></td>
          <td><%= answer.user.name %></td>
          <td><%= answer.question_id %></td>
          <td><%= link_to 'Show', answer %></td>
          <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
          <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Answer', new_answer_path %> |
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>
<% if ((logged_in?) && (get_UAL? == 4))%>
<h2>Questions</h2>

<%= link_to 'New Question', new_question_path %>

<table>
  <thead>
    <tr>
      <th>Reputation</th>
      <th>Title</th>
      <th>Question</th>
      <th>User</th>
      <th>Answers</th>
      <th>Flagged</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.rep %></td>
        <td><%= question.title %></td>
        <td><%= question.content %></td>
        <td>asked by <%= link_to question.user.name, user_path(question.user) %> (rep: <%= question.user.rep %>)</td>
        <td><%= link_to question.answers.count, answers_path %></td>
        <td><%= question.is_flagged %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>
<% else %>
  <h2>You are not authorized to view this page.</h2>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', courses_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<% if ((logged_in?) && (can_view_crs(@question.course.id))) %>
<% set_question(@question.id) %>
<h2>Question posted in <%= link_to @question.course.name, course_path(@question.course) %> (<%= link_to @question.course.academic_label, course_path(@question.course) %>)</h2>

<% if @question.is_flagged == 1 %>
<h3>This Question has been Flagged</h3>
<% else %>
<h2><%= @question.title %> (Rep: <%= @question.rep %>)</h2>
<%= @question.content %><br><br>
<% end %>
asked by <%= link_to @question.user.name, user_path(@question.user) %> (Rep: <%= @question.user.rep %>)<br>

<% if !owns_question(@question.id) %>
<%= link_to 'Vote Up', upvote_question_path(@question) %>
<%= link_to 'Vote Down', downvote_question_path(@question) %>
<% end %>
<% if owns_question(@question.id) %>
<%= link_to 'Edit', edit_question_path(@question) %>
<% end %>
<% if (get_UAL? >= 2) %>
<%= link_to 'Flag', flag_question_path(@question) %>
<% end %>


<br><br><h2><b>Answers:</b></h2>
<% if @question.answers.count == 0 %>
  <b>No answers yet.</b><br><br>
<% end %>
<%= link_to 'New Answer', new_answer_path %><br><br>
<% if @question.answers.count > 0 %>
<table>
    <!--<tr>
      <th>Content</th>
      <th>User</th>
      <th>Question</th>
      <th>Flagged</th>
      <th colspan="3"></th>
    </tr>-->
    <% @question.answers.each do |answer| %>
      <% if answer.is_flagged == 1 %>
        <tr>
          <td><b>This Answer Has Been Flagged!</b></td>
        </tr>
        <tr>
          <td>Content Hidden.</td>
        </tr>
        <tr>
          <td>by <%= link_to answer.user.name, user_path(answer.user) %> (Rep: <%= answer.user.rep %>)</td>
        </tr>
      <% else %>
        <tr>
          <td><%= answer.content %> (Rep: <%= answer.rep %>)</td>
        </tr>
        <tr>
          <td>by <%= link_to answer.user.name, user_path(answer.user) %> (Rep: <%= answer.user.rep %>)</td>
        </tr>
        <tr>
          <td><% if (!owns_answer(answer.id)) %><%= link_to 'Vote Up', upvote_answer_path(answer) %> 
          <%= link_to 'Vote Down', downvote_answer_path(answer) %> <% end %>
          <% if ((owns_answer(answer.id)) || (get_UAL? == 4)) %> <%= link_to 'Edit', edit_answer_path(answer) %> <% end %>
          <% if (get_UAL? >= 2) %> <%= link_to 'Flag', flag_answer_path(answer) %> <% end %>
          <% if (get_UAL? == 4) %> <%= link_to 'Remove', answer, method: :delete, data: { confirm: 'Are you sure?' } %> <% end %></td>
        </tr>
      <% end %>
    <% end %>
</table>
<% end %>
<% if @question.answers.count > 0 %>
  <br><%= link_to 'New Answer', new_answer_path %>
<% end %>
<% else %>
  <h2>You are not authorized to view this page.</h2>
<% end %>