config/routes.rb
Rails.application.routes.draw do
  #root 'courses#index' #old root
  root 'sessions#new' #new root -- for login page
  
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/moderator', to: 'control_panels#moderator'
  get '/registrar', to: 'control_panels#registrar'
  
  resources :course2users do
    
  end
  
  resources :courses do
    
  end
  resources :answers do
    member {get 'flag'}
    member {get 'unflag'}
    member {get 'upvote'}
    member {get 'downvote'}
  end
  resources :questions do
    member {get 'flag'}
    member {get 'unflag'}
    member {get 'upvote'}
    member {get 'downvote'}
  end
  resources :users do
    
  end
  
  
  #resources :questions, :shallow => true do 
  #  resources :answers
  #end
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :questions
    has_many :answers
    has_many :courses, :through => :course2users
    has_many :course2users
    accepts_nested_attributes_for :course2users
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
  
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to registrar_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to registrar_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :accesslevel, :academic_label)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    #def add_course(course_id)
    #   course2users.add_course(course_id, @user.id)
    #end <-- I don't think this even did anything; pretty sure I wrote it and forgot to delete it
end

app/views/users/_form.html.erb
<% if ((logged_in?) && (get_UAL? >= 3))%>
  <%= form_for(user) do |f| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %><br/>
      <%= f.email_field :email %>
    </div>
    <br>
    <div class="field">
      <%= f.label :accesslevel %><br> <!-- fixed the radio buttons for ya. remember, in order for the values to be submitted, you need to use "f."-->
      <%= f.radio_button(:accesslevel, 1) %>
        <%= f.label(:accesslevel_1, "Student") %> |
      <%= f.radio_button(:accesslevel, 2) %>
        <%= f.label(:accesslevel_2, "Faculty") %> |
      <%= f.radio_button(:accesslevel, 3) %>
        <%= f.label(:accesslevel_3, "Registrar") %> |
      <%= f.radio_button(:accesslevel, 4) %>
        <%= f.label(:accesslevel_4, "Moderator") %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% else %>
  <h2>You are not authorized to view this page.</h2>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<% if logged_in? %>
  <h2>Users</h2>
  
  <% if @users.count == 0 %>
    <b>No Users yet.</b>
  <% else %>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Reputation</th>
          <th>Access Level</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% if ((logged_in?) && (get_UAL? >= 3))%>        <!-- registrar and mod can see all users -->
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.name, user %></td>
              <td><%= link_to user.email, user %></td>
              <td><%= user.rep %></td>
              <td><%= user.accesslevel %></td>
              <!--<#% if ((logged_in?) && (get_UAL? >= 3)) %>-->
              <td><%= link_to 'Edit', edit_user_path(user) %></td>
              <td><%= link_to 'Remove', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <!--<#% end %>-->
            </tr>
          <% end %>
        <% else %>                                       <!-- users and faculty can see only other class-relevant users -->
          <% @users.each do |user| %>
            <% if shares_course_id(user) %>
            
              <!--<#% if (@user.course_id == user.course_id)%> doing shit-->
              <tr>
                <td><%= link_to user.name, user %></td>
                <td><%= link_to user.email, user %></td>
                <td><%= user.rep %></td>
                <td><%= user.accesslevel %></td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% else %>
    <h2>Please Log-In to view Users.</h2>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% if logged_in? %>
  <% if get_UAL? >= 3 %>
    <% set_regis_cr_user(@user.id) %>
  <% end %>
  <h2><%= @user.name %>'s Profile</h2>
  
  <p>
    <strong>Reputation:</strong>
    <%= @user.rep %>
  </p>
  
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <% if ((logged_in?) && (get_UAL? >= 3)) %>
    <%= link_to 'Edit', edit_user_path(@user) %><br><br>
  <% end %>
  
  <% if (@user.accesslevel <= 2) %>
  <p>
    <strong>Courses:</strong>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
        </tr>
      </thead>
    
      <tbody>
        <% if @user.courses.count == 0 %>
          <tr><td colspan="2">This user is not enrolled in any courses yet.</td></tr>
        <% else %>
          <% @user.courses.each do |course| %>
            <tr>
              <td><%= link_to course.name, course %> (<%= course.academic_label %>)</td>
              <td><%= course.description %></td>
            <% if (get_UAL? >= 3) %>
            <% c_id = course %>
            <% c2u = Course2user.find_by(course_id: c_id, user_id: @user.id) %>
              <td><%= link_to 'Remove', course2users(c2u.id), method: :delete, data: { confirm: 'Are you sure?' }%></td>
            <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <% if ((logged_in?) && (get_UAL? >= 3)) %>
      <%= link_to 'Add_Course', new_course2user_path %><br><br>
    <% end %>
  </p>
  <% end %>
  
  <h2>Questions: <%= @user.questions.count %></h2>
  <% if @user.questions.count == 0 %>
  <b>This User has not asked any questions yet.</b>
  <% else %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Course</th>
        <th>Answers</th>
        <th colspan="2"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @user.questions.each do |question| %>
        <% if question.is_flagged == 1 %>
          <tr>
            <td>This Question has been Flagged</td>
            <td>in <%= link_to question.course.name, course_path(question.course) %> (<%= question.course.academic_label %>)</td>
            <td><%= question.answers.count %></td>
          </tr>
        <% else %>
          <tr>
            <td><%= link_to truncate(question.title, :length => 50, :separator => ' ', :omission => "..."), question_path(question) %> (Rep: <%= question.rep %>)</td>
            <td>in <%= link_to question.course.name, course_path(question.course) %> (<%= question.course.academic_label %>)</td>
            <td><%= question.answers.count %></td>
            <td><%= link_to 'Edit', edit_question_path(question) %></td>
            <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <% end %>
  
  <br><h2>Answers: <%= @user.answers.count %></h2>
  <% if @user.answers.count == 0 %>
  <b>This User has not answered any questions yet.</b>
  <% else %>
  <table>
    <thead>
      <tr>
        <th>Answer</th>
        <th>Question</th>
        <th>Course</th>
        <th colspan="2"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @user.answers.each do |answer| %>
        <% if answer.is_flagged == 1 %>
          <tr>
            <td>This Answer has been Flagged</td>
            <td><%= link_to truncate(answer.question.title, :length => 50, :separator => ' ', :omission => "..."), question_path(answer.question) %> </td>
            <td>in <%= link_to answer.question.course.name, course_path(answer.question.course) %> (<%= answer.question.course.academic_label %>)</td>
          </tr>
        <% else %>
          <tr>
            <td><%= truncate(answer.content, :length => 50, :separator => ' ', :omission => "...") %> (Rep: <%= answer.rep %>)</td>
            <td><%= link_to answer.question.title, question_path(answer.question) %> </td>
            <td>in <%= link_to answer.question.course.name, course_path(answer.question.course) %> (<%= answer.question.course.academic_label %>)</td>
            <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
            <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <% end %>
<% else %>
  <h2>Please Log-In to view this User.</h2>
<% end %>